tap "caskroom/cask"
tap "caskroom/versions"

brew "axel"
brew "vim"
brew "elixir"
brew "postgresql"
brew "git"
brew "youtube-dl"
brew "node"
brew "rbenv"
brew "ruby-build"
brew "reattach-to-user-namespace"
brew "tmux"
brew "zsh"
brew "watchman"
