tap "caskroom/cask"
tap "neovim/homebrew-neovim"

brew "python"
brew "neovim", args: ["HEAD"]
brew "postgresql"
brew "rethinkdb"
brew "axel"
brew "git"
brew "youtube-dl"
brew "node"
brew "rbenv"
brew "ruby-build"
brew "reattach-to-user-namespace"
brew "tmux"
brew "zsh"
brew "watchman"
